configfile: "config/config.yaml"
rule polish&select
	input:
		featurecount="counts/featurecount/raw_featurecount/{datasets}/{rawCounts}.txt",
		meta="Metadata/{wildcards.datasets}/{MetaDdata}.csv"
	output:
		"counts/featurecount/selected_featurecounts/{wildcards.datasets}/{rawCounts}_raw.txt"
	Script:
		"Scripts/polish&select.R"
        
	
rule plot:
	input:
		"Metadata/{}.csv"
	output:
	Script:
		"Scripts/Meta/plot.R"
