configfile: "config/config.yaml"
rule all:
	input:
		select_data:"rules.polish_select.output",
		Norm_data:"rules.Normalization_filter.output"
		plot_done:"rules.plots.output.PCA"
rule polish_select:
	input:
		featurecount="counts/featurecount/raw_featurecount/{datasets}/{rawCounts}.txt"
		meta="Metadata/{wildcards.datasets}/{MetaDdata}.csv"
	output:
		"counts/featurecount/selected_featurecounts/{wildcards.datasets}/{rawCounts}_raw.txt"
	Script:
		"Scripts/polish&select.R"
        
rule Normalization_filter:
	input:
		counts=rules.polish_select.output
		meta="Metadata/{wildcards.datasets}/{MetaDdata}.csv"
		gtf="gtf/{}.gtf.gz"
	params:
		norm=config["Norm_method"]
	output:
		"counts/normalized/{params.norm}/{wildcards.datasets}/{rawCounts}_{params.norm}.txt"
	Script:
		"Scripts/norm_filter.R"
		
		
rule plots:
	input:
		data="rules.Normalization_filter.output"
		raw="rules.polish_select.output"
		meta="rules.polish_select.input.meta"
	output:
		boxplot="plots/{params.norm}/boxplots/{wildcards.datasets}_countDist.jpeg"
		LibSize="plots/{params.norm}/LibSize/{wildcards.datasets}_LibSize.jpeg"
		PCA="plots/{params.norm}/LibSize/{wildcards.datasets}_PCA.jpeg"
	params:
		norm=config["Norm_method"]
		PCA_color=config["PCA_color"]
	Script:
		"Scripts/All_plots.R"
