Samples:
    - mayo_TCX
    - mayo_CER
    - msbbBM22
    - msbbBM44
    - msbbBM10
    - msbbBM36
Annotation: Data/Refs/gencode.v33.chr_patch_hapl_scaff.annotation.gtf.gz
Conditions:
    - AD
    - control
