featurecounts:
    - mayo_CER
    - mayo_TCX
    - msbb
 sample_name:
    - msbb
 Condition:
    - AD
    - control
 MetaData1:
    - AD_msbbBM10
    - AD_msbbBM22
    - AD_msbbBM36
    - AD_msbbBM44
    - control_msbbBM10
    - control_msbbBM22
    - control_msbbBM36
    - control_msbbBM44
 MetaData2:
    - AD_mayo_CER
    - AD_mayo_TCX
    - control_mayo_CER
    - control_mayo_TCX

